[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA redirect - todas as rotas do Vue devem ir para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200